### ISSUE TITLE
multiple select dropdown

### ISSUE THREAD

**Issue by lucidBug** [trebuchetty/Handsontable-select2-editor#7]
hello guys, I need to do a multi select dropdown. I followed the comments on  #4   and modified all the code. but doesn't work. any suggestions? (I am new to handsontable, found it out recently)

**Comment by trebuchetty** [comment]
Do you have a jsfiddle?

**Comment by lucidBug** [comment]
@trebuchetty yes , here it is  http://jsfiddle.net/lucidBug/8ab5n028/
I commented some pieces since was not working ...

**Comment by trebuchetty** [comment]
I looked through your jsfiddle. You're not even using my Select2 editor. You don't even have Select2 included in the js files. I think you may be unaware of what my editor is actually used for. 

This editor is for helping to create a select2 dropdown as a handsontable editor. This allows you to have more complicated and IMO useful dropdowns within handsontable that the autocomplete built-in editor doesn't provide. Multiselect would certainly meet that specification.

Maybe I'll need to update the documentation for this to better explain how to use it. I also have some changes to make so that it's compatible with the latest versions of Select2 and Handsontable.

**Comment by abugroup** [comment]
Hi I'm using your select2 editor working perfect but I also need  multi selection can you guide me how to do this

**Comment by abugroup** [comment]
Hi Please help to complete this.

**Comment by hansgru** [comment]
This "component" does not seems to work :(  :
 - it's not clear for what version of Handsontable to use: #9
 - no working example or demo demonstrating it at all.

**Comment by abugroup** [comment]
Hi Thank your for your response

I'm using "handsontable-0.15.0-beta2"

Here is the demo
http://jsfiddle.net/4mpyhbjw/38/


Thank you

**Comment by abugroup** [comment]
Here is the another
http://jsfiddle.net/4mpyhbjw/40/

**Comment by abugroup** [comment]
Hi any update please I have no choice.

**Comment by hansgru** [comment]
> Hi any update please I have no choice.

Unfortunately we were not able to make it work with handsontable :(., 
We refactored our application with master-detail screens, and the detail we implemented with this multi-select field: http://w2ui.com/web/demos/#!fields/fields-4

**Comment by abugroup** [comment]
Hi thank you for giving this grid table I also refactored from handsontable to w2ui can you help me how to  implement multi select option in column inline editing?

**Comment by aadrian** [comment]
> can you help me how to implement multi select option in column inline editing?

This is disabled in W2UI for now: https://github.com/vitmalina/w2ui/issues/911
because of "width" reasons.
(for inline grid editing)
You could vote for that issue so that the author allows the multi-select compoment to be rendered inline too.

As I said before we refactored and used a "master-detail" mode for the fields that we could not edit inline. So we have "detail" forms like in the link I mentioned above for the fields that can't be rendered at the moment inline.
The detail

**Comment by aadrian** [comment]
**master** is a W2UI grid with inline edit mode, with the following column configuration:
  - *read only columns* - grayed out that are never editable (e.g. ID column, creation date, etc)
  - *editable columns* - normally editable inline columns/cells for simple values
  - *button columns* - like the read only columns but with an ```onClick``` event handler so that they open a popup (a **detail** form) where fields that can't be edited inline like multi-select, color picker, big text area fields  are allowed here in the popup form since it has enough place.

This way, for most stuff the user edits inline, and for those few exceptions a popup with a form is used.

**Comment by trebuchetty** [comment]
@abugroup, you were close. The only change you needed was the 'multiple' option for the select2 options.
select2Options: { 
                        data: optionsList,
                        dropdownAutoWidth: true,                        
                        width: 'resolve',
                       multiple: true
                    }

Your renderer would then need some small adjustments to show the multiple selections correctly.

**Comment by sagar-mindstix** [comment]
Hi Guys,
Any update for multi selected item in dropdown using ngHandson table. I also wanted to use multi selected dropdown feature in my app.

**Comment by trebuchetty** [comment]
ngHandsontable isn't currently supported with this editor. I believe there's a pull request to add this functionality, but I haven't merged it into a separate branch yet.
